name: Stakeholders
on:
  pull_request:

jobs:
  stakeholders-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo "âœ… Stakeholders have approved"

      - name: Set status
        if: always()
        run: exit 0
